apiVersion: v1
kind: Pod
metadata:
  namespace: development
  name: ngnixapp
  labels:
    gname: standAlonePod
spec:
  containers:
  - name: ngnixapp1
    image: nginx:1.14.2
    ports:
    - containerPort: 4567
  - name: ngnixapp2
    image: redis
    ports:
    - containerPort: 8000
