apiVersion: v1
kind: Pod
metadata:
    name: ngnixapp
    namespace: dev
    labels:
      gname: StandAloneNgnixPod
spec:
  containers:
    - name: ngnixapp1
      image: nginx:1.14.2
      ports:
        - containerPort: 4567
    - name: myredisapp1
      image: redis:7.0
      ports:
        - containerPort: 8080