apiVersion: v1
kind: Pod
metadata:
  name: ngnixapp
  labels:
    gname: standAlonePod
spec:
  containers:
  - name: ngnixapp1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: ngnixapp2
    image: nginx:1.14.2
    ports:
    - containerPort: 80