apiVersion: v1
kind: Pod
metadata:
    name: ngnixapp
    namespace: dev
    labels:
      gname: StandAloneNgnixPod
spec:
  - name: ngnixapp1
    image: nginx:1.14.2
    ports:
      - containerPort:4567